---
title: "Future or Fugazi"
author: "Tom Oates"
date: "9/15/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
For the "economic" plot 
```{r}
#get the libraries
# install.packages("tidyverse")
library(tidyverse)
theme_set(theme_light(base_size = 20))

#import the data
library(readxl)
unemployment <- read_excel("unemployment")
interest_rate <- read.csv("/cloud/project/interest_rate.csv")
facebook <- read_excel("facebook")
#change valuation to log2 so fits on the plot
facebook <- facebook %>%
  mutate(valuation = log2(valuation))

#sort the dates out
unemployment <- unemployment %>%
  mutate(date = parse_date_time(date, orders = "my"))

interest_rate <- interest_rate %>%
  mutate(date = parse_date_time(date, orders = "my"))

# merge and gather 
rates_data <- merge(interest_rate, unemployment, all = TRUE)
rates_data <- merge(rates_data, facebook, all = TRUE)

rates_data<- rates_data %>%
  gather(type, rate, interest_rate:valuation , factor_key=TRUE)

# plot
ggplot(rates_data, aes(date,rate))+geom_point(aes(colour=type))+geom_smooth(aes(colour=type), span=0.3, se=FALSE)+ylim(c(0,15)) +
  theme(legend.position = "none") +
  labs(x="Date",y="")

```
For the histogram of Pubmed citations containing "Machine Learning"
```{r}
#Import data (dwnloaded from pubmed after searching 'machine learning')
timeline <- read.csv("/cloud/project/timeline.csv")
ggplot(timeline, aes(x=year, y=count)) + geom_col() +
  labs(x="Year", y="PubMed Citations")
```
For the plots used in the explanation of machine learning
```{r}
library(MASS)
# install.packages("GGally")
library(GGally)

# For initial plot 
l <- ggplot(Boston, aes(lstat, medv))+geom_point(color="dodgerblue3") +
  labs(x="Predictor", y="Output")
# With smooth line  
l + geom_smooth()
# To show as a classification problem 
ggplot(Boston, aes(lstat, medv))+geom_point(aes(col=as.factor(chas))) +
  scale_color_manual(values = c("dodgerblue3", "orangered3")) +
  labs(x="Predictor", y="Output") +
  theme(legend.position = "none")
  
```

